### ISSUE TITLE
Navigation to sub-boards is broken in Firefox and Tor Browser

### ISSUE THREAD

**Issue by antiphase0** [Nullchan/nullchan#4]
I'm running a local instance of ZeroNet 0.3.6 rev915 on Ubuntu 15.10. When visiting `http://127.0.0.1:43110/0chan.bit` in Firefox-based browsers, clicking on any of the sub-board links from the main page loads the sub-board pages but they are greyed out and superimposed with a modal dialog that reads:

> You have opened this page by clicking on a link. Please, confirm if you want to load this site.

![0chan - zeronet - tor browser_002_small](https://cloud.githubusercontent.com/assets/17594310/13464821/c05a3ff8-e08a-11e5-9020-a0e380af9dcd.jpg)

The dialog has an "Open site" button which when pressed opens a new tab with endlessly spinning gears underneath an identical dialog:

![0chan - zeronet - tor browser_003_small](https://cloud.githubusercontent.com/assets/17594310/13464795/a9beb508-e08a-11e5-8483-cbd7c341cd40.jpg)

The sub-board pages load fine when I use Chromium browser.

Broken:
- Firefox 44.0.2 (fresh installation, default configuration)
- Tor Browser 5.5.2, based on Firefox 38.6.1 (fresh installation, default configuration)

Works:
- Chromium 48.0.2564.116

**Comment by antiphase0** [comment]
Just tested again, and it works in Firefox and Tor Browser now. Did you push new code to the site?

**Comment by sthetz** [comment]
Hello! Thank you for this input and can you please check this again? I rolled out a supposed fix for these problems this morning, in my Firefox on OSX everything works correctly now. Please confirm.

**Comment by antiphase0** [comment]
Yes, tested just now and all sub-board links still work in Tor Browser and Firefox (and Chromium). Nice!
