### ISSUE TITLE
How to set up?

### ISSUE THREAD

**Issue by apoapostolov** [Nullchan/nullchan#5]
What I do: 

1. Create site
2. Copy nullchan in the created site dir
3. Sign site
4. Publish site

I get black screen and no content, is there any readme on how to install nullchan?

**Comment by sthetz** [comment]
I'm writing a small guide on installation right now, will close this once I test and confirm that it works.

**Comment by apoapostolov** [comment]
I checked it minute ago.

So far I only added 

"ignore": "(.git|data/users|node_modules|data/0chan.db|update_files.rb|package.json|content.example.json|LICENSE|README.md|js/engine/.*|js/templates|js/libs)",

Since the rest fields were already existing.

**Comment by sthetz** [comment]
https://github.com/Nullchan/nullchan/blob/master/README.md
